### ISSUE TITLE
SRE, Mythes vs Réalités

### ISSUE THREAD

**Issue by hgomez** [sre-france/meetups#115]
### Author's Name

hgomez

### Author's Bio

Plus de 30 de carrière dans l'industrie IT, 2/3 coté développement (Dev), 1/3 coté opérations (Run).

Mes sujets de prédilections du moment tournent autour des pratiques SRE, de l'Observabilité, les usines logicielles, le Dev Embarqué et le bas niveau.

Je suis tombé dans l'OpenSource, il y a longtemps, avec la conviction qu'une communauté active et des standards ouverts créent de bien meilleures solutions. 

J'ai commencé à geeker sur des machines 8bits et aujourd'hui je les restaure ;)

### Expected time

Standard talk (~40 min)

### Language

- [X] French
- [ ] English

### Abstract

Il y a encore trop souvent une vision fantasmée de l'activité SRE, ce qui entraine mécaniquement des retours à la réalité qui sont parfois douloureux.

L'intention de ce talk est de faire un retour d'expérience SRE, sur ce que nous avons pu voir, [Jean-Pascal](https://twitter.com/jpthiery) et [Henri](https://twitter.com/hgomez), dans des entreprises de petites à grandes, des jeunes pousses ou de vénérables institutions.

L'idée est de vous armer pour éviter le maximum de déconvenues et rendre l'activité SRE la plus profitable et efficiente possible.

Références

-     https://www.youtube.com/watch?v=d5R_G5JV4vk (SRE, la théorie et la pratique)
-     https://www.youtube.com/watch?v=AvdwiwZLLLM (hype driven development / halte au feu)
-     https://www.youtube.com/watch?v=HJC6r8Dr7cQ (L'Observabilité ou comment connaitre l'état de son systéme)

**Comment by hgomez** [comment]
Bonjour @pabluk 

Pas de soucis ;)

Le format lighting talks sera malheureusement trop court pour ce sujet qui est sur l'humain plus que la technique et je ne pourrais pas avoir Jean-Pascal avec moi pour un SRE Meetup sur Chambéry.

Bien amicalement

**Comment by pabluk** [comment]
Pas de soucis Henri, merci encore :pray: et en tout cas ça fait plaisir de savoir qu'il y a des gens autour du DevOps/OSS dans le coin. A une prochaine fois !
