### ISSUE TITLE
The other side of the story: what it takes to build & operate a Serverless engine

### ISSUE THREAD

**Issue by NoKriK** [sre-france/meetups#35]
__author name__:
Yann Léger - @yann_eu

__author bio__:
Co-Founder of Koyeb, a company delivering a next-generation serverless platform, Yann spent the last 10 years building cloud service providers in the infrastructure space from scratch.
Passionated by cloud computing, he has an excellent understanding of the industry and all the underlying infrastructure, from datacenters to the software stack running on hypervisors.
After building Scaleway, which started as a serverfull IaaS provider with BareMetal ARM servers, Yann realized that the future was serverless :)

__expected time__ :

- [ ] lightning talk (~ 5 min)
- [x] 20 min

__language__:

- [x] :fr:
- [x] :uk:

**this talk will be done**:
- [x] remotely
- [x] physically

(both work on my side)

__abstract__:
**The other side of the story: what it takes to build & operate a Serverless engine**
Using serverless certainly comes with its own set of challenges, but there is another side of the story which is not often told: how serverless platforms are built and what are their technological limitations.
At Koyeb, we’re a cloud service provider building a serverless platform. I will walk you through how we built our own serverless engine, the key decisions we had to make and what our architecture looks like. We now have a purpose-built stack based on Nomad, Firecracker, and Kuma.
We will talk about the underlying technological components of serverless platforms including orchestration, virtualization, and networking.

**Comment by pabluk** [comment]
Thanks for your contribution @NoKriK :+1: it's a great topic and I think everyone is interested to know more about the backstage of a serverless platform.

We are planning the next meetup that probably will be scheduled for the first week of December, so I'll keep you posted on that.

**Comment by NoKriK** [comment]
Awesome! Let me know when you have a date I can lock.

Looking forward to it :)

**Comment by pabluk** [comment]
Hi @NoKriK due to the current covid-19 situation and the enforcement of remote working policies in most of the companies where we could host the event, we have decided to re-schedule the December meetup to mid-January, and I'll keep you posted on any news. Thanks :pray:

**Comment by pabluk** [comment]
Hi @NoKriK we've scheduled the next meetup on January 28, 2022 at 7pm and due to the covid situation it will be full online. Would it still be okay for you to present your talk? Thanks!

**Comment by pabluk** [comment]
Hello @NoKriK, just in case if you are available on May 5th we are organizing a new meetup in Bordeaux. It will be and in-person/online hybrid event for guests and speakers, so if you're still up for talk about Koyeb and the internals of a serverless platform we'll be happy to welcome you.

**Comment by NoKriK** [comment]
Hi @pabluk,

My sincere apologies, I missed your updates, they got lost in my inbox.
Definitely happy to join the next one!

Let me know,

**Comment by pabluk** [comment]
Hi @NoKriK no problem, there will always be a new meetup to share your talk and you'll be welcome! I'll contact you when we start to organize the next. Thanks.
