### ISSUE TITLE
Kubernetes @ no-scale

### ISSUE THREAD

**Issue by guilhem** [sre-france/meetups#68]
### Author's Name

Guilhem Lettron

### Author's Bio

SRE indépendant / Partisan du DevOps,
Podcasteur [@DevObs_Podcast](https://twitter.com/DevObs_Podcast)

### Expected time

Lightning talk (~15 min)

### Language

- [X] French
- [ ] English

### Abstract

Kubernetes est souvent présenté comme l'outil de gestion pour les grandes entreprises, les grands déploiements.
Dans ce talk, établie sur une expérience réelle @themecloud.io, nous verrons comment Kubernetes profite également aux petits projets, aux (toutes) petites équipes avec pourtant beaucoup de "legacy".

**Comment by tormath1** [comment]
Super! C'est vrai que Kubernetes est souvent associé à "très grosses charges" et projets complexes donc c'est super intéressant d'aborder le sujet sous un autre angle.

Nit-pick:
> Dans ce talk, basée sur une expérience réelle

Je sais pas si tu veux laisser `basée` comme ça, j'aurais tendance à le mettre `basé` mais bon ... Un talk? Une talk? :joy:
